/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThreatIntelRouteImport } from './routes/threat-intel'
import { Route as AudioVideoRouteImport } from './routes/audio-video'
import { Route as IndexRouteImport } from './routes/index'

const ThreatIntelRoute = ThreatIntelRouteImport.update({
  id: '/threat-intel',
  path: '/threat-intel',
  getParentRoute: () => rootRouteImport,
} as any)
const AudioVideoRoute = AudioVideoRouteImport.update({
  id: '/audio-video',
  path: '/audio-video',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audio-video': typeof AudioVideoRoute
  '/threat-intel': typeof ThreatIntelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audio-video': typeof AudioVideoRoute
  '/threat-intel': typeof ThreatIntelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audio-video': typeof AudioVideoRoute
  '/threat-intel': typeof ThreatIntelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/audio-video' | '/threat-intel'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/audio-video' | '/threat-intel'
  id: '__root__' | '/' | '/audio-video' | '/threat-intel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AudioVideoRoute: typeof AudioVideoRoute
  ThreatIntelRoute: typeof ThreatIntelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/threat-intel': {
      id: '/threat-intel'
      path: '/threat-intel'
      fullPath: '/threat-intel'
      preLoaderRoute: typeof ThreatIntelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audio-video': {
      id: '/audio-video'
      path: '/audio-video'
      fullPath: '/audio-video'
      preLoaderRoute: typeof AudioVideoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AudioVideoRoute: AudioVideoRoute,
  ThreatIntelRoute: ThreatIntelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
